language: node_js
node_js: 0.1
script: true
deploy:
  provider: openshift
  user: clara.attermo@gmail.com
  password:
    secure: lv/IaUcZfMhTd7XnApQ0R5zKqLKDQjLnniAOcPX5ldAiMwCSsdy0h4cqyrOeh42vWagUcA15B7c98KfgD2BkWZKFrwaFeSj8IKkvu3KX2BvoYLGssHadiFangS055ESrUUjpbvJ6pZVG5koR+guGk5rEOHKSVabrqut5g6ZT9Cxl06ZSltcfTuRnjb26/RonZEori3+Qgv29W5++GdPFlohN3RwB38hM0OYTvGCjfxBg6KHJ5bqBxv5UQEheiAdaEKNRzqMSAKm9w/n3wDLZMpi14porTWh3SM6p1V5x2PlXvq54Gob9wk14eDJOyI/Ns9A2GuS80IxzxZiJ1K9Q0OrZnEKdzwA+FHoUEOYwX7VCu5V/tL98PSX30uzve2wpckzut3NVRcpTwoLiFZo7ACwQE4Dnv3Y8/bfmo4n4d9rSMEaVkNrv/AvxGuQHO9rlw9/R7gBIBu2zqGtJ3EzjSTLWr5zWCYOF7NrTpsaxzRlOegwGCvbLKXht9sqWTMZ0aPBFbTsOlMSyj5miIGyrxqM2wLMEiMN/LkrSlMdrHC3xNMDYfOGHBH4fIuv7gQZ5qtErzwH3lamPl5ONyCjPSiQhrnh5fpDDl3wV69fTcy88R00T1UYKvkICrZNGYnZVZ11MGknFA7MklnDf02ZN5bsBA43AZuSMYypX+xI/ZSk=
  app: fyrton
  domain: cattermo
  on:
    repo: cattermo/fyrton
