language: node_js
node_js: 0.1
script: true
deploy:
  provider: openshift
  user: clara.attermo@gmail.com
  password:
    secure: SCI5+IvL2IZTBPtBeu0RbdK3SrK+VYAkc9rePhLdk9bUblW2e8B8vi4nOFnl9s+E/3s6+JPWdTrT7uV9irPFZnAXYdrT0zay+LzgUzV+9m3E7xMQNkcN4bACGekj/Jb6l+98wwQ9FX5BuBaaXwIe0Ql23KRjXG5qNxWzBFwHPjeqFnyJVRxxIHHFmn78cHSUU75227kMf9Ssb6FUGjGIyyO3jPsE2UwccEHvlvJ60utwoeTEULYFj0coMVww/YQk6oU3VsCN80WzYRyAGVTTUW8P/SFNhkUR2oE1MWSrW+6TvTjisuGe2GdhHdpTD6lxnnmEqXzuOZM6T+l3nsTAIy2IcaRbbMlu+ujZMvCzOBuFJdxkJlAiXwn7pShGuQrUiNIOULR2ux+oKpnDYeqYbH3qvCBfSRn+mxujzV3inKk84gOf1/PPE0pCJHAcVUFHl5sO6GSWaGkrJKbJOX9OqyaWH07OKVSjevL4H3DF4MGaADoYnmJAqUe9VcdtP1Vf3exumxQ27Lf5fwmh9mXBzcqYrsnHt0a0lsoEWQ+AsbLEOSD5iyXiCardgDW6jLzyBbYe6D1p7ht/Lp/Rz8GGHMuU6ZeOQdL/JiprU99jy4TM1mSKoCploM1Igp5E2eMg31Ddhi6BaPEa+kzuZa/pewAlTorZKO/nHZ5LFthF/uE=
  app: fyrton
  domain: cattermo
  on:
    repo: cattermo/fyrton
