version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e9:b3:79:0b:80:69:21:19:28:a0:c7:34:84:0f:3b:b8"
      - checkout
      - run: npm install
      - run: npm run generate
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master